title: Revolutionary biotechnologies
author: Lorena Dai
email: lorena@brown.edu
description: > # this means to ignore newlines until "baseurl:"
  Transfer revolutionary science into breakthrough technologies
theme: minima

# social links
twitter_username: your-twitter-handle
github_username:  your-github-handle

show_excerpts: true # set to false to remove excerpts on the homepage
